[project]
name = "{{ cookiecutter.project_slug }}"
version = "0.1.0"
description = "{{ cookiecutter.project_description }}"
authors = [
    { name = "{{ cookiecutter.author_name }}" }
]
requires-python = ">={{ cookiecutter.python_version }}"
dependencies = [
    "loguru>=0.7.3",
    "ipython>=9.15.0",
    "python-dotenv>=1.2.2",
]


[dependency-groups]
dev = [
    "pytest>=8.0.0",
    "rust-just",
]