[project]
name = "cc"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "cookiecutter>=2.7.1",
    "gitpython>=3.1.52",
    "loguru>=0.7.3",
    "tool>=0.8.0",
    "typer>=0.27.0",
    "rust-just",
]

[project.scripts]
cc-cli = "cc.cli:main"

[dependency-groups]
dev = [
    "black>=26.5.1",
    "isort>=8.0.1",
    "pre-commit>=4.6.0",
    "ty>=0.0.61",
]

[tool.isort]
profile = "black"
